name: build

on: 
  push:
    branches:
    - master
    - release/*
  pull_request:
    branches:
    - master  

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v1
    
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    
    - name: Build Docs
      run: mvn clean package --file pom.xml #-Ppublish-site 
      
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: target/generated-docs # The folder the action should deploy.
        CLEAN: true # Automatically remove deleted files from the deploy br  
       
  automerge:
    name: Merge pull request
    runs-on: ubuntu-latest
    needs: [build]
    if: github.base_ref == 'master' && github.actor == 'dependabot[bot]'
    steps:
      - name: Merge
        uses: actions/github-script@0.2.0
        with:
          script: |
            github.pullRequests.merge({
              owner: context.payload.repository.owner.login,
              repo: context.payload.repository.name,
              pull_number: context.payload.pull_request.number
            })
          github-token: ${{github.token}}
